## Numpy Arrays

- rank 1 array
- rank 2 array

In [4]:
import numpy as np
a_1 = np.array([12,3,4,5])
print(a_1)
print(a_1.shape) # array shape
print(a_1[0],a_1[1])

[12  3  4  5]
(4,)
12 3


In [10]:
a_2 = np.array([[1,2,3,4],[4,3,2,1]])
print(a_2)
print(type(a_2))
print(a_2.shape)
print(a_2[0],a_2[0,0],a_2[1,1])

[[1 2 3 4]
 [4 3 2 1]]
<class 'numpy.ndarray'>
(2, 4)
[1 2 3 4] 1 3


## Numpy Arrays - creation

- [numpy basic](https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation)
- [CS231n课程笔记翻译：Python Numpy教程](https://zhuanlan.zhihu.com/p/20878530?refer=intelligentunit)

In [16]:
z = np.zeros((2,3))
print(z.shape)
print(z)
b = np.ones((3,4))
print(b)
c = np.full((2,2),7)
print(c)
r= np.random.random((4,4))
print(r)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7]
 [7 7]]
[[0.72734492 0.98691471 0.12618118 0.46682799]
 [0.34179401 0.38683268 0.65776491 0.64701091]
 [0.11957205 0.95714212 0.09489415 0.46504619]
 [0.17192758 0.90693754 0.93849813 0.97130198]]
